version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fiscaluno_institutions
        ports:
            - 8888:5000
        links:
            - postgres:DATABASE_URL

    postgres:
        image: postgres
        restart: always
